name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt flake8 pytest coverage

    # Step 4: Lint with flake8
    - name: Lint with flake8
      run: flake8 .

    # Step 5: Run tests with pytest
    - name: Run tests
      run: pytest

    # Step 6: Check code coverage
    - name: Check code coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml

    # Step 7: Upload coverage report to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    # Step 8: Report linting errors (if any)
    - name: Report linting errors
      if: failure()
      run: echo "❌ Linting errors found. Please fix them before merging."