name: Push to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  push-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy plotly scikit-learn statsmodels streamlit nltk huggingface_hub
          
      - name: Push to HF Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Push to HF Hub
          python -c "
          import os
          from huggingface_hub import HfApi

          hf_token = os.environ['HF_TOKEN']  # Retrieve HF_TOKEN from environment
          api = HfApi()

          # Create repo (or ensure it exists)
          api.create_repo(
              repo_id='canstralian/cve-analysis-platform',
              private=True,
              exist_ok=True,
              token=hf_token
          )

          # Upload folder contents
          api.upload_folder(
              folder_path='.',
              repo_id='canstralian/cve-analysis-platform',
              token=hf_token
          )
          "