name: Push to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  push-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy plotly scikit-learn statsmodels streamlit nltk
          
      - name: Push to HF Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Install huggingface_hub
          pip install huggingface_hub
          
          # Configure git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Push to HF Hub
          python -c "
          from huggingface_hub import HfApi
          api = HfApi()
          api.create_repo(
              'cve-analysis-platform',
              private=True,
              exist_ok=True
          )
          api.upload_folder(
              folder_path='.',
              repo_id='cve-analysis-platform',
              token='${{ secrets.HF_TOKEN }}'
          )
          "
