name: ML Workflow Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual triggering
    inputs:
      run_type:
        description: 'Type of run: full_pipeline or test_only'
        required: true
        default: 'full_pipeline'

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run data processing
      - name: Run data processing
        run: |
          python data_processing.py

      # Step 5: Train model
      - name: Train the model
        if: inputs.run_type == 'full_pipeline'
        run: |
          python model_training.py

      # Step 6: Run visualizations
      - name: Generate visualizations
        run: |
          python visualizations.py

      # Step 7: Launch Streamlit app
      - name: Test Streamlit app
        run: |
          python streamlit_app.py